version: "3"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      NODE_ENV: production
      accessKeyId: ASIASZTQJ7PKBD2DCR33
      secretAccessKey: 1IoKR5qU50yMlC3iPRnjLvlUX1TJ5uw14Z40/bN+
      sessionToken: FwoGZXIvYXdzEDkaDMykSbvwz2CVD0SkyiLHAW7J/uh6hGfwAFnwP/QlVxiXI2Itqdu6pE/Ac7zc+o2jPp3FU/Ow5hImaiIou1STpRwo8LQzWU98e+BJz4GmcJm/aHYg8rCZm5+dhKPVNzMWtxqHzfrqNtJE7QxkWVXp/oko/L+jWGAdQ09knwdJyzoaF/7+BF2i9MPRqkq4G+ySlkoqQJmTa1O2qTMn6LbmYAXQanGTuscGpWLIKqVSJ7cYQHMggQcmZ1uaiKIzs93VIWGV5vH3eGBOdCDu3PPA74YH5eKobggo+b2VowYyLe+CEgzTw7rxpaEi+apGH2WUiiL3pB1fDjf9ii4JKjBTICYspeHdoSd3E6xOhg==   

    restart: always
